import { CrmData } from "./types";

// Datos iniciales de ejemplo (puedes borrarlos desde la app o editarlos).
// Reproducen el contenido de las capturas para que la plataforma no arranque vacía.
export const SEED: CrmData = {
  clientes: [
    {
      id: "cli-luis",
      nombre: "Luis",
      empresa: "RenovePlac",
      tipoNegocio: "Reformas de pladur",
      inicio: "2026-04-30",
      implementacion: 680,
      mantenimientoMes: 39,
    },
    {
      id: "cli-pablo",
      nombre: "Pablo",
      empresa: "Sinag",
      tipoNegocio: "Agencia de marketing",
      inicio: "2026-04-24",
      implementacion: 5580,
      mantenimientoMes: 390,
    },
    {
      id: "cli-neus",
      nombre: "Neus",
      empresa: "Luxury Reforms",
      tipoNegocio: "Empresa de reformas",
      inicio: "2026-04-23",
      implementacion: 990,
      mantenimientoMes: 125,
    },
    {
      id: "cli-enebie",
      nombre: "Enebie",
      empresa: "Bitzen Mineria",
      tipoNegocio: "Mineria de crypto",
      inicio: "2026-04-15",
      implementacion: 150,
      mantenimientoMes: 25,
    },
    {
      id: "cli-juan",
      nombre: "Juan Villuendas",
      empresa: "Nutricion Juan Villuendas",
      tipoNegocio: "Centro de dietetica",
      inicio: "2026-03-01",
      implementacion: 250,
      mantenimientoMes: 45,
    },
    {
      id: "cli-quico",
      nombre: "Quico Reig",
      empresa: "Quico Barber",
      tipoNegocio: "Peluqueria",
      inicio: "2026-03-01",
      implementacion: 90,
      mantenimientoMes: 30,
    },
  ],
  proyectos: [
    {
      id: "pro-sinag",
      nombre: "Sinag",
      cliente: "Pablo",
      descripcion:
        "Plataforma de automatización de campañas para la agencia de marketing.",
      estado: "pendiente",
      etiquetas: ["Demo", "Propuesta"],
      createdAt: "2026-05-02",
    },
    {
      id: "pro-miguel",
      nombre: "Miguel Ventanas PVC",
      cliente: "Miguel",
      descripcion:
        "Quiere 3 demos: Control de obra. Se sube el albarán al software, la IA lo analiza y lo manda al equipo de obra. Al final del día rellenan un formulario.",
      estado: "pendiente",
      etiquetas: ["Propuesta"],
      createdAt: "2026-05-05",
    },
    {
      id: "pro-luxury",
      nombre: "Luxury Reforms",
      cliente: "Neus",
      descripcion:
        "Quieren un chatbot para filtrar clientes y agendar citas. Un CRM donde lleguen todos estos leads de manera ordenada.",
      estado: "en_progreso",
      etiquetas: ["Propuesta"],
      createdAt: "2026-05-08",
    },
    {
      id: "pro-enebie",
      nombre: "Enebie Bitzen Mineria",
      cliente: "Enebie",
      descripcion:
        "Quieren una plataforma para generar artículos para su web optimizados con SEO.",
      estado: "pendiente_cliente",
      etiquetas: ["Demo", "Propuesta"],
      createdAt: "2026-04-20",
    },
    {
      id: "pro-juan",
      nombre: "Nutrición Juan Villuendas",
      cliente: "Juan Villuendas",
      descripcion:
        "Web + sistema de reservas para el centro de dietética. Entregado y en funcionamiento.",
      estado: "terminado",
      etiquetas: ["Propuesta"],
      createdAt: "2026-03-10",
    },
  ],
  tareas: [
    {
      id: "tar-inmobiliaria",
      titulo: "Enviar Propuesta Inmobiliaria",
      descripcion: "Propuesta de chatbot para filtrar clientes de idealista.",
      estado: "pendiente",
      prioridad: "baja",
      tipo: "otro",
      fechaLimite: "2026-04-16",
      hora: null,
      asignadoA: "Iker",
      createdAt: "2026-04-01",
    },
    {
      id: "tar-izan",
      titulo: "Llamar Izan Piso 13",
      descripcion: "",
      estado: "pendiente",
      prioridad: "alta",
      tipo: "otro",
      fechaLimite: "2026-09-01",
      hora: "09:00",
      asignadoA: "Iker",
      createdAt: "2026-05-20",
    },
    {
      id: "tar-pablo",
      titulo: "Entrega a Pablo",
      descripcion: "Desarrollo.",
      estado: "en_progreso",
      prioridad: "alta",
      tipo: "otro",
      fechaLimite: "2026-05-11",
      hora: "09:00",
      asignadoA: "Iker",
      createdAt: "2026-05-01",
    },
    {
      id: "tar-piso31",
      titulo: "Demo Piso 31",
      descripcion:
        "Es un estudio de tatuajes. Quieren un chatbot para filtrar clientes en WhatsApp. Servicios: Tatuajes, Depilación láser, Eliminación láser.",
      estado: "en_progreso",
      prioridad: "media",
      tipo: "demo",
      fechaLimite: "2026-05-06",
      hora: "09:30",
      asignadoA: "Iker",
      createdAt: "2026-04-25",
    },
    {
      id: "tar-mailboxes",
      titulo: "Demo Mail Boxes",
      descripcion: "Hay que hacer un chatbot.",
      estado: "completada",
      prioridad: "alta",
      tipo: "demo",
      fechaLimite: "2026-04-14",
      hora: "10:00",
      asignadoA: "Iker",
      createdAt: "2026-04-02",
    },
    {
      id: "tar-paro",
      titulo: "Pedir Paro",
      descripcion: "",
      estado: "completada",
      prioridad: "alta",
      tipo: "otro",
      fechaLimite: "2026-04-15",
      hora: "09:30",
      asignadoA: "Iker",
      createdAt: "2026-04-03",
    },
  ],
  eventos: [
    {
      id: "ev-1",
      titulo: "Demo Piso 31",
      descripcion: "Presentación del chatbot al estudio de tatuajes.",
      tipo: "demo",
      estado: "en_progreso",
      fecha: "2026-06-16",
      horaInicio: "09:30",
      horaFin: "10:30",
      asignadoA: "Iker",
    },
    {
      id: "ev-2",
      titulo: "1ª Reunión Sinag",
      descripcion: "Reunión inicial para definir el alcance del proyecto.",
      tipo: "reunion",
      estado: "pendiente",
      fecha: "2026-06-17",
      horaInicio: "11:00",
      horaFin: "12:00",
      asignadoA: "Iker",
    },
    {
      id: "ev-3",
      titulo: "Llamada Pablo",
      descripcion: "Seguimiento de la entrega.",
      tipo: "otro",
      estado: "pendiente",
      fecha: "2026-06-18",
      horaInicio: "16:00",
      horaFin: "16:30",
      asignadoA: "Iker",
    },
    {
      id: "ev-4",
      titulo: "Demo Luxury Reforms",
      descripcion: "Demo del chatbot de filtrado de clientes.",
      tipo: "demo",
      estado: "pendiente",
      fecha: "2026-06-19",
      horaInicio: "10:00",
      horaFin: "11:00",
      asignadoA: "Iker",
    },
    {
      id: "ev-5",
      titulo: "Entrega Enebie",
      descripcion: "Entrega de la plataforma de generación de artículos SEO.",
      tipo: "otro",
      estado: "completada",
      fecha: "2026-06-15",
      horaInicio: "12:00",
      horaFin: "13:00",
      asignadoA: "Iker",
    },
  ],
};
